#!groovy
/**
 * Jenkins pipeline to run basic code checks.
 */

/**
 * Kill already started job.
 * Assume new commit takes precedence and results from previous
 * unfinished builds are not required.
 * This feature doesn't play well with disableConcurrentBuilds() option
 */
@Library('corda-shared-build-pipeline-steps')
import static com.r3.build.BuildControl.killAllExistingBuildsForJob
killAllExistingBuildsForJob(env.JOB_NAME, env.BUILD_NUMBER.toInteger())

/*
 * A placeholder of computed NexusIQ application id
 */

def nexusAppId = null

pipeline {
    agent { label 'standard' }
    options {
        timestamps()
        timeout(time: 3, unit: 'HOURS')
    }

    stages {
        stage('Detekt check') {
            steps {
                /**
                 * Since this build starts Gradle multiple times,
                 * *do* start it as a daemon.
                 */
                sh "./gradlew clean detekt"
            }
        }

        stage('Compilation warnings check') {
            steps {
                sh "./gradlew --info " +
                    "-Pcompilation.warningsAsErrors=true " +
                    "compileAll"
            }
        }

        stage('Sonatype Check') {
            steps {
                sh "./gradlew -Pcompilation.warningsAsErrors=false " +
                    "jar"
                script {
                    sh "./gradlew properties | grep -E '^(version|group):' >version-properties"
                    def version = sh (returnStdout: true, script: "grep ^version: version-properties | sed -e 's/^version: //'").trim()
                    def groupId = sh (returnStdout: true, script: "grep ^group: version-properties | sed -e 's/^group: //'").trim()
                    def artifactId = 'corda'
                    nexusAppId = "jenkins-${groupId}-${artifactId}-${version}-PR"
                }
                nexusPolicyEvaluation (
                        failBuildOnNetworkError: false,
                        iqApplication: manualApplication(nexusAppId),
                        iqScanPatterns: [[scanPattern: 'node/capsule/build/libs/corda*.jar']],
                        iqStage: 'build'
//                        jobCredentialsId: 'nexusiq_evaluator'
                )
            }
        }

        stage('No API change check') {
            steps {
                sh "./gradlew generateApi"
                sh ".ci/check-api-changes.sh"
            }
        }

        stage('Deploy Nodes') {
            steps {
                sh "./gradlew jar deployNodes"
            }
        }
    }

    post {
        always {
            /**
             * Make sure Gradle daemon is stopped after this build
             */
            sh "./gradlew --stop && true"
        }
        cleanup {
            deleteDir() /* clean up our workspace */
        }
    }
}
